[package]
name = "rustzen-zipper"
version = "0.1.0"
edition = "2024"
description = "Rust CLI tool for zipping dist folders"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.48", features = ["derive"] }
walkdir = "2.5.0"
zip = "5.1.1"
